const emoji = {
  "chocolate-bar": "🍫",
  clock: "⌚",
  "crossed-fingers": "🤞",
  "crystal-ball": "🔮",
  dancer: "💃",
  "exploding-head": "🤯",
  gemstone: "💎",
  joy: "😂",
  koala: "🍋",
  lollipop: "🍭",
  "see-no-evil": "🙈",
  sparkles: "✨",
  watermelon: "🍉",
  taxi: "🚕",
};
